services:
  app:
    build: .
    depends_on:
      - db
    environment:
      ENV: testing

  test:
    build: .
    depends_on:
      - db
    env_file:
      - .env.testing
    command: ["pytest"]

  db:
    image: postgres:15
    environment:
      POSTGRES_USER: test_user
      POSTGRES_PASSWORD: test_pass
      POSTGRES_DB: test_db
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
