services:
  app:
    build: .
    depends_on:
      - db
    env_file:
      - .env
    ports:
      - "8000:8000"

  test:
    build: .
    depends_on:
      - db
    env_file:
      - .env
    command: ["pytest"]

  db:
    image: postgres:15
    env_file:
      - .env
    ports:
      - "5432:5432"

