services:
  app:
    build: .
    depends_on:
      - db
    env_file:
      - .env
    volumes:
      - ./app:/app
    command: uvicorn main:app --reload --host 0.0.0.0 --port 8000
    ports:
      - "8000:8000"

  test:
    build: .
    depends_on:
      - db
    env_file:
      - .env
    command: ["pytest"]

  db:
    image: postgres:15
    env_file:
      - .env
    ports:
      - "5432:5432"

