name: CI

on: 
  push:
    branches: 
      - "master"

  pull_request:
    branches:
      - "master"

jobs:
  docker-test:
    runs-on: "ubuntu-latest"

    steps:
      - name: checkout repo
        uses: actions/checkout@v3

      - name: Build Docker Image
        run: docker build -t feedingtracker . 

      - name: Run Docker Image Container
        run: docker run --rm feedingtracker pytest

      - name: Set Up Environment Variables from Secrets
        run: |
          echo "POSTGRES_USER=${{ secrets.POSTGRES_USER }}" >> $GITHUB_ENV
          echo "POSTGRES_PASSWORD=${{ secrets.POSTGRES_PASSWORD }}" >> $GITHUB_ENV
          echo "POSTGRES_HOST=${{ secrets.POSTGRES_HOST }}" >> $GITHUB_ENV
          echo "POSTGRES_DATABASE=${{ secrets.POSTGRES_DB }}" >> $GITHUB_ENV
          echo "POSTGRES_PORT=${{ secrets.POSTGRES_PORT }}" >> $GITHUB_ENV