name: CI

on: 
  push:
    branches: 
      - "master"
  pull_request:
    branches: 
      - "master"

jobs:
  docker-test:
    runs-on: ubuntu-latest

    env:
      POSTGRES_USER: ${{ secrets.POSTGRES_USER }}
      POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
      POSTGRES_DB: ${{ secrets.POSTGRES_DB }}
      POSTGRES_HOST: db
      POSTGRES_PORT: 5432

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Build and start services in detached mode
        run: docker-compose up --build -d

      - name: Run tests in a temporary container
        run: docker-compose run --rm test

      - name: Tear down services
        run: docker-compose down
