name: CI

on: 
  push:
    branches: 
      - "master"

  pull_request:
    branches:
      - "master"

jobs:
  docker-test:
    runs-on: "ubuntu-latest"

    env:  # Set environment variables for the entire job
      POSTGRES_USER: ${{ secrets.POSTGRES_USER }}
      POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
      POSTGRES_HOST: ${{ secrets.POSTGRES_HOST }}
      POSTGRES_DB: ${{ secrets.POSTGRES_DB }}
      POSTGRES_PORT: ${{ secrets.POSTGRES_PORT }}
      
    steps:
      - name: checkout repo
        uses: actions/checkout@v3

      - name: Print environment variables
        run: |
          echo "POSTGRES_HOST: $POSTGRES_HOST"
          echo "POSTGRES_PORT: $POSTGRES_PORT"

      - name: Build Docker Image
        run: docker build -t feedingtracker . 

      - name: Run Docker Image Container
        run: docker run --rm feedingtracker pytest