name: CI

on: 
  push:
    branches: 
      - "master"
  pull_request:
    branches: 
      - "master"

jobs:
  docker-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

       - name: Build and start services
        run: docker compose up --build -d

      - name: Run tests
        run: |
          docker compose run --rm \
            -e POSTGRES_USER=${{ secrets.POSTGRES_USER }} \
            -e POSTGRES_PASSWORD=${{ secrets.POSTGRES_PASSWORD }} \
            -e POSTGRES_DB=${{ secrets.POSTGRES_DB }} \
            -e POSTGRES_HOST=db \
            -e POSTGRES_PORT=5432 \
            test

      - name: Tear down services
        run: docker compose down
