name: CI

on: 
  push:
    branches: 
      - "master"
  pull_request:
    branches: 
      - "master"

jobs:
  docker-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Create .env file from secrets
        run: |
          echo "POSTGRES_USER=${{ secrets.POSTGRES_USER }}" >> .env
          echo "POSTGRES_PASSWORD=${{ secrets.POSTGRES_PASSWORD }}" >> .env
          echo "POSTGRES_DB=${{ secrets.POSTGRES_DB }}" >> .env
          echo "POSTGRES_HOST=db" >> .env
          echo "POSTGRES_PORT=5432" >> .env

      - name: Build and start services
        run: docker compose up --build -d

      - name: Run tests
        run: docker compose run --rm --env-file .env test

      - name: Tear down services
        run: docker compose down
